name: aag
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  # Librerías científicas básicas
  - numpy
  - pandas
  # Herramientas de ploteo
  - matplotlib
  - seaborn
  # - pycairo  # Backend de igraph.plot
  # Jupyter Lab + registro de ambientes ("kernels") en Jupyter
  - jupyterlab
  - ipykernel
  # Librerías de grafos
  - networkx
  - python-igraph
  # Miscelánea
  - requests  # Para hacer consultas a APIs externas
  - geopandas  # Utilidades de análisis y ploteo de data geográfica
